import re
print("--------------------------")
heroRegex = re.compile(r'Batman|Tina')
mo1 = heroRegex.search('Batman and Tina Fey.')
print(mo1.group())
print("--------------------------")
mo2 = heroRegex.search('Tina Fey and Batman.')
print(mo2.group())
print("--------------------------")
batRegex = re.compile(r'Bat(man|mobile|copter|bat)')
mo = batRegex.search('Batmobile lost a wheel')
print(mo.group())
print("++++++++++++++++++++++++++++++")
print(mo.group(1))
print("--------------------------")

batRegex = re.compile(r'Bat(wo)?man')
mo1 = batRegex.search('The Adventures of Batman')
print(mo1.group())
print("--------------------------")
mo2 = batRegex.search('The Adventures of Batwoman')
print(mo2.group())
print("--------------------------")
phoneRegex = re.compile(r'(\d{3}-)?\d{3}-\d{4}')
mo1 = phoneRegex.search('My number is 415-555-4242')
print(mo1.group())
print("--------------------------")
mo2 = phoneRegex.search('My number is 555-4242')
print(mo2.group())
print("--------------------------")
